name: Laptop Price MLflow CI/CD Pipeline

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow==2.19.0 pandas numpy scikit-learn

      - name: Run MLflow Project
        run: |
          mlflow run MLProject/ --env-manager=local

      - name: Get Exact Model Path
        run: |

          MLMODEL_FILE=$(find . -name "MLmodel" -type f | head -n 1)

          echo "MLmodel ditemukan di:"
          echo "$MLMODEL_FILE"

          if [ -z "$MLMODEL_FILE" ]; then
            echo "ERROR: MLmodel tidak ditemukan"
            find . -maxdepth 6 -type d | sort
            exit 1
          fi

          MODEL_DIR=$(dirname "$MLMODEL_FILE")

          echo "MODEL_DIR=$MODEL_DIR" >> $GITHUB_ENV

          echo "Model Directory:"
          echo "$MODEL_DIR"

      - name: Upload Artifact to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: model-artifacts
          path: ${{ env.MODEL_DIR }}

      - name: Build Docker Model
        run: |
          mlflow models build-docker \
            --model-uri "${{ env.MODEL_DIR }}" \
            --name "radenscc23/laptop-price-model:latest"

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: |
          docker push radenscc23/laptop-price-model:latest
