name: Laptop Price MLflow CI/CD Pipeline

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow==2.19.0 pandas numpy scikit-learn

      - name: Run MLflow Project
        run: |
          mlflow run MLProject/ --env-manager=local

      - name: Get Exact Model Path
        run: |
          MLMODEL_FILE=$(find . -name "MLmodel" -type f | head -n 1)

          if [ -z "$MLMODEL_FILE" ]; then
            echo "ERROR: MLmodel tidak ditemukan"
            exit 1
          fi

          echo "========== ISI MLMODEL =========="
          cat "$MLMODEL_FILE"

          MODEL_DIR=$(dirname "$MLMODEL_FILE")
          echo "MODEL_DIR=$MODEL_DIR" >> $GITHUB_ENV
          echo "MODEL_DIR=$MODEL_DIR"

      - name: Copy model artifacts for Docker build
        run: |
          cp -r "${{ env.MODEL_DIR }}" ./model

      - name: Upload Artifact to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: model-artifacts
          path: ${{ env.MODEL_DIR }}

      - name: Log in to Docker Hub (manual)
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login docker.io \
            -u "${{ secrets.DOCKER_USERNAME }}" \
            --password-stdin

      - name: Build Docker Image
        run: |
          docker build \
            -t radenscc23/laptop-price-model:latest \
            -f Dockerfile \
            .

      - name: Push Docker Image
        run: |
          docker push radenscc23/laptop-price-model:latest
